# Generated by Django 5.1.3 on 2024-11-22 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profiels',
            old_name='is_acttive',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user_profiels',
            old_name='is_sttaf',
            new_name='is_staff',
        ),
    ]
