# Generated by Django 5.1.3 on 2024-11-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_rename_is_acttive_user_profiels_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profiels',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
