# Generated by Django 5.1.3 on 2024-11-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_alter_user_profiels_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profiels',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
